/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yifanlu_Josh */

#ifndef _Included_com_yifanlu_Josh
#define _Included_com_yifanlu_Josh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yifanlu_Josh
 * Method:    ADDCONSOLEALIAS
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_ADDCONSOLEALIAS
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_yifanlu_Josh
 * Method:    CREATECONSOLESCREENBUFFER
 * Signature: (ZZI)J
 */
JNIEXPORT jlong JNICALL Java_com_yifanlu_Josh_CREATECONSOLESCREENBUFFER
  (JNIEnv *, jclass, jboolean, jboolean, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    FILLCONSOLEOUTPUTATTRIBUTE
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_FILLCONSOLEOUTPUTATTRIBUTE
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    FILLCONSOLEOUTPUTCHARACTER
 * Signature: (JCIII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_FILLCONSOLEOUTPUTCHARACTER
  (JNIEnv *, jclass, jlong, jchar, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLECURSORINFO
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETCONSOLECURSORINFO
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLEDISPLAYMODE
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_yifanlu_Josh_GETCONSOLEDISPLAYMODE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLEFONTSIZE
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETCONSOLEFONTSIZE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLEHISTORYINFO
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETCONSOLEHISTORYINFO
  (JNIEnv *, jclass);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLEMODE
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_yifanlu_Josh_GETCONSOLEMODE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLESCREENBUFFERSIZE
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETCONSOLESCREENBUFFERSIZE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLETITLE
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLETITLE
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETTEXTATTRIBUTE
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETTEXTATTRIBUTE
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    CLEARSCREEN
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_CLEARSCREEN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLECURSORPOSITION
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLECURSORPOSITION
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETSTDHANDLE
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_yifanlu_Josh_GETSTDHANDLE
  (JNIEnv *, jclass);

/*
 * Class:     com_yifanlu_Josh
 * Method:    WRITECONSOLE
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_WRITECONSOLE
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
