/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yifanlu_Josh */

#ifndef _Included_com_yifanlu_Josh
#define _Included_com_yifanlu_Josh
#ifdef __cplusplus
extern "C" {
#endif
#undef com_yifanlu_Josh_STD_INPUT_HANDLE
#define com_yifanlu_Josh_STD_INPUT_HANDLE -10L
#undef com_yifanlu_Josh_STD_OUTPUT_HANDLE
#define com_yifanlu_Josh_STD_OUTPUT_HANDLE -11L
#undef com_yifanlu_Josh_STD_ERROR_HANDLE
#define com_yifanlu_Josh_STD_ERROR_HANDLE -12L
/*
 * Class:     com_yifanlu_Josh
 * Method:    CREATECONSOLESCREENBUFFER
 * Signature: (ZZI)J
 */
JNIEXPORT jlong JNICALL Java_com_yifanlu_Josh_CREATECONSOLESCREENBUFFER
  (JNIEnv *, jclass, jboolean, jboolean, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    FILLCONSOLEOUTPUTATTRIBUTE
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_FILLCONSOLEOUTPUTATTRIBUTE
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    FILLCONSOLEOUTPUTCHARACTER
 * Signature: (JCIII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_FILLCONSOLEOUTPUTCHARACTER
  (JNIEnv *, jclass, jlong, jchar, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLECURSORINFO
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETCONSOLECURSORINFO
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLEDISPLAYMODE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yifanlu_Josh_GETCONSOLEDISPLAYMODE
  (JNIEnv *, jclass);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLEFONTSIZE
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETCONSOLEFONTSIZE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLEHISTORYINFO
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETCONSOLEHISTORYINFO
  (JNIEnv *, jclass);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLEMODE
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_yifanlu_Josh_GETCONSOLEMODE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLEORGINIALTITLE
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yifanlu_Josh_GETCONSOLEORGINIALTITLE
  (JNIEnv *, jclass);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLESCREENBUFFERINFO
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETCONSOLESCREENBUFFERINFO
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLESELECTIONINFO
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETCONSOLESELECTIONINFO
  (JNIEnv *, jclass);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLETITLE
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yifanlu_Josh_GETCONSOLETITLE
  (JNIEnv *, jclass);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCONSOLEWINDOW
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_yifanlu_Josh_GETCONSOLEWINDOW
  (JNIEnv *, jclass);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETCURRENTCONSOLEFONT
 * Signature: (JZ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETCURRENTCONSOLEFONT
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETLARGESTCONSOLEWINDOWSIZE
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_GETLARGESTCONSOLEWINDOWSIZE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETNUMBEROFCONSOLEINPUTEVENTS
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_yifanlu_Josh_GETNUMBEROFCONSOLEINPUTEVENTS
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETNUMBEROFCONSOLEMOUSEBUTTONS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yifanlu_Josh_GETNUMBEROFCONSOLEMOUSEBUTTONS
  (JNIEnv *, jclass);

/*
 * Class:     com_yifanlu_Josh
 * Method:    GETSTDHANDLE
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_yifanlu_Josh_GETSTDHANDLE
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    PEEKCONSOLEINPUT
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_PEEKCONSOLEINPUT
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    READCONSOLEINPUT
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_READCONSOLEINPUT
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    READCONSOLE
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yifanlu_Josh_READCONSOLE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    READCONSOLEOUTPUT
 * Signature: (JIIII)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_yifanlu_Josh_READCONSOLEOUTPUT
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    READCONSOLEOUTPUTATTRIBUTE
 * Signature: (JIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_READCONSOLEOUTPUTATTRIBUTE
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    READCONSOLEOUTPUTCHARACTER
 * Signature: (JIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yifanlu_Josh_READCONSOLEOUTPUTCHARACTER
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SCROLLCONSOLESCREENBUFFER
 * Signature: (JIIIIIIIIIICI)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SCROLLCONSOLESCREENBUFFER
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jchar, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLEACTIVESCREENBUFFER
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLEACTIVESCREENBUFFER
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLECURSORINFO
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLECURSORINFO
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLECURSORPOSITION
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLECURSORPOSITION
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLEDISPLAYMODE
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLEDISPLAYMODE
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLEHISTORYINFO
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLEHISTORYINFO
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLEMODE
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLEMODE
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLESCREENBUFFERINFOEX
 * Signature: (JIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLESCREENBUFFERINFOEX
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLESCREENBUFFERSIZE
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLESCREENBUFFERSIZE
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETTEXTATTRIBUTE
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETTEXTATTRIBUTE
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLETITLE
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLETITLE
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLEWINDOWINFO
 * Signature: (JZIIII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLEWINDOWINFO
  (JNIEnv *, jclass, jlong, jboolean, jint, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCURRENTCONSOLEFONTEX
 * Signature: (JZIII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCURRENTCONSOLEFONTEX
  (JNIEnv *, jclass, jlong, jboolean, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETSTDHANDLE
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETSTDHANDLE
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_yifanlu_Josh
 * Method:    WRITECONSOLE
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_WRITECONSOLE
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_yifanlu_Josh
 * Method:    WRITECONSOLEINPUT
 * Signature: (JI[II)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_WRITECONSOLEINPUT
  (JNIEnv *, jclass, jlong, jint, jintArray, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    WRITECONSOLEOUTPUT
 * Signature: (J[[IIIII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_WRITECONSOLEOUTPUT
  (JNIEnv *, jclass, jlong, jobjectArray, jint, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    WRITECONSOLEOUTPUTATTRIBUTE
 * Signature: (J[IIII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_WRITECONSOLEOUTPUTATTRIBUTE
  (JNIEnv *, jclass, jlong, jintArray, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    WRITECONSOLEOUTPUTCHARACTER
 * Signature: (J[IIII)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_WRITECONSOLEOUTPUTCHARACTER
  (JNIEnv *, jclass, jlong, jintArray, jint, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    BEEP
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_BEEP
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    CLEARSCREEN
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_CLEARSCREEN
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_yifanlu_Josh
 * Method:    SETCONSOLEFONT
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_yifanlu_Josh_SETCONSOLEFONT
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
